### ISSUE TITLE
After clicking the main.exe, the app sayd this and just quits (我点击 main.exe 后，应用程序说了这个并自己退出了 ;v; 求

### ISSUE THREAD

**Issue by User741543** [OnesoftQwQ/XTCEasyRootPlus#3]
After clicking the main.exe, the app sayd this and just quits (我点击 main.exe 后，应用程序说了这个并自己退出了 ;v; 求
log>检查最新版本

log>发现新版本:1.9

log>开始下载新版本......

log>Traceback (most recent call last):
  File "C:\Users\belug\AppData\Local\Temp\ONEFIL~1\main.py", line 64, in <module>
  File "C:\Users\belug\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 1026, in __init__
  File "C:\Users\belug\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 1538, in _execute_child
OSError: [WinError 1392] The file or directory is corrupted and unreadable

**Comment by Huofeinb** [comment]
好像最近只能用easyroot，plus用不了

**Comment by OnesoftQwQ** [comment]
最近Plus关闭使用，因为目前的Root流程如果碰到最新系统会遇到一些很严重的问题

**Comment by longjiajia1234** [comment]
> 好像最近只能用easyroot，plus用不了

谁有earyroot的链接，找了好久没找到
